name:                concurrency
version:             0.1.0.0
github:              "githubuser/concurrency"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/concurrency#readme>

default-extensions:
  - OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- concurrent-extra
- random
- warp
- bytestring
- http-types
- wai
- text

library:
  source-dirs: src

executables:
  concurrency-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - concurrency

tests:
  concurrency-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - concurrency
